### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tjouni** [lauriap/OnlineRecipes#1]
Projekti ladattu 23.8 klo 10:30

Käytettävyys:

Sovellus on jäsennelty mielestäni järkevästi ja sitä on kohtalaisen helppo käyttää. Ainoa käytettävyysongelma, jonka huomasin oli, että kesken reseptin lisäämisen puuttuvien ainesosien lisääminen kantaan on hankalaa.

Ainesosan poistaminen poistaa ainesosat kaikista resepteistä, joissa niitä on käytetty. Tämä ei välttämättä ole toivottavaa. Ymmärrän kyllä, että toiminnallisuus on tällainen luultavasti kurssin CRUD-vaatimusten takia.

Saman käyttäjänimen voi rekisteröidä kahteen kertaan. Rekisteröin sovellukseen käyttäjän testinick/testi2 ja sillä kirjautuminen onnistui.

Koodi:

Koodi on selkeää ja helposti ymmärrettävää. Projektirakenne vastaa kurssimateriaalissa määriteltyä rakennetta. Templateissa on käytetty järkevästi url_for-tyyppisiä linkkejä, ja muu koodi on pääosin järkevän näköistä.

recipes/views.py-tiedostossa on hieman erikoinen rakenne monessa eri funktiossa (esim. 10 erillistä try/except-rakennetta). Nämä voisi korvata mielestäni näppärästi for-loopeilla.

layout.html-tiedostossa on käytetty <font> tagia. Bootstrapin kanssa olisi suositeltavaa korvata tämä esim <p class="text.white"> tagilla.

**Comment by lauriap** [comment]
Kiitos arviosta! Yritän ottaa nämä huomioon parhaani mukaan jatkokehityksessä.
