### ISSUE TITLE
Vertaisarvio 2

### ISSUE THREAD

**Issue by Topi62** [lauriap/OnlineRecipes#2]
# Vertaisarvio

Repositio ladattu ma 2.9.2019 klo 18:40

## Yleistä
Testattu sovellusta Herokussa kokeilemalla kaikkia toimintoja. Näkymä oli miellyttävä, toiminnot pääosin selkeitä käyttää.

Kloonattu repositio ja käyty läpi kaikki tiedostot. Rakenteessa kansio signup, jossa forms.py ja views.py. Sopisi paremmin 
mielestäni auth kansioon. Kyse on kirjautumistoiminnoista auth kansion models.py taulua user käyttäen.

README selkeä, mutta todela lyhyt. Requimentsissa sekä Flask-SQLAlchemy että SQLAlchemy, __init__.py tiedostossa importataan SQLAlchemy Flask-SQLAlchemystä. onko tarpeen?

luokat ja metodit lyhyitä ja yhteen tehtävään tarkoitettuja.

Bootstrap käytössä, hienoa.

## dokumentaatio
Tietokantakaavio selkeä, vastaa toteutusta. 

Käyttötapauksia roolille User, mutta kaikki User palauttaa roolin Admin kaikille.

Asennusohjeelle ei vielä linkkiä readmessä, mutta ohje melko kattava. Sovellus käyttää paikallisesti sqliteä, ei postgresqlää, ja riippuvuudet voisi asentaa komennolla ```pip install -r requiments.txt``` ,jolloin ei tarvita erikseen Flaskin tms. asennusta.

## datamodel
Recipeingredient
amount Column nyt String. Jos olisi jaettu kahtia, lukumäärä int, mittayksikkö string, ja reseptille merkitty annosmäärä, voisi käyttäjä vaihtamalla annosmäärää sivulla, saada aineksien tarvittavat määrät. Joillekin on vaikea laskea esim. jos ainesta tarvitaan 3/4 litraa neljälle hengelle, paljonko tarvitaan kuudelle.

recipes instructions Column String 1000 kirjainta, yleensä riittää, mutta usein on ihan liikaa. Olisiko mahdollista jakaa työvaiheisiin, jolloin yhden työvaiheen kuvailuun riittäisi vähemmän merkkejä ja lyhyet reseptit eivät veisi tilaa tietokannasta sen skaalautuessa. Samallahan tuohon saisi lisäkentät kunkin työvaiheen tarvittaville työvälineille, kestolle jne.

Ainakaan toistaiseksi ei ole käyttöä Columnille date_modified taulussa User. 

## forms

[Onko tarpeen](../tree/master/application/recipes/forms.py) kyselyiden nimen vaihto ennen niiden käyttöä QuerySelectField query_factory argumenttinä?

validoinnit hyvin vähäisiä ja lähinnä varmistavat, että syöte on annettu. Liian pitkästä syötteestä ei varoiteta, mutta toki tietokannan kentät ovat pitkiä. Kuitenkin tietokantaan voi lisätä aineksia ilman nimeä.

Update ja delete lomakkeilla QuerySelectFieldeille on annettu argumentti allow_blanks=True, joka johtaa sovelluksessa virhetilanteeseen, jos käyttäjä ei valitsekaan kentälle arvoa. False hoitaisi tästä ilmoituksen käyttäjälle.

Kymmenen kentän lomakkeet ovat kömpelöitä. Olisiko järkevämpi lisätä ainekset yksi kerrallaan ja palata tallentamisen jälkeen samalle sivulle, jossa reseptin tiedot näkyvillä. Samoin poisto yksi kerrallaan.

## queries
Listoja tai queryselectfieldeille palauttavat kyselyt listaavat asiat id järjestyksessä, kun käyttäjälle mielestäni mielekkäämpi järjestys esimerkiksi aineksen valinnalle olisi aakkosjärjestys eli kentän name mukaan.

## views
[recipes/start_page](../tree/master/application/recipes/views.py)
Palauttaisi index.html:n mutta tätä ei käytetä missään, index sivu palautetaan  application/views.py koodilla.

## templates
Useampia delete, list, update html-templateja voisi käyttää pienellä vaivalla sekaisin, muutama muutama rivi sivuilla voisi olla muuttujissa niitä kutsuttaessa ja lomakkeen ollessa tarpeen ```{% if form is defined %}``` mahdollistaisi sen käytön.

## Heroku
Sovellus aukeaa ja toimii siis muutoin odotesti, paitsi jos update tai delete sivuilla ei valitse indeksiä muutettavalle.

## Kokonaisuutena
Sovelluksesta jää vähän suppea kuva.

**Comment by lauriap** [comment]
Kiitos kommenteista! Osa oli asioita, joita en ollut edes tullut ajatelleeksi (esim. pip install -r requirements.txt, {% if form is defined %} jne.), osa taas tiedossa, mutta kurssin laajuuden ja fokuksen huomioon ottaen tietoisesti valittuja (10 raaka-ainetta vs. dynaaminen raaka-aineiden lisäys).

Pyrin vielä viimeisellä viikolla parantamaan sovellusta mahdollisuuksien mukaan kommenttien pohjalta.
